In [5]:
from gym.spaces import Box, Discrete, Graph

In [6]:
box = Box(low= 0, high= 4, shape=(3,3), dtype = int)

In [7]:
actions = Discrete(100)

In [8]:
graph = Graph(box, actions)

In [9]:
graph

Graph(Box(0, 4, (3, 3), int32), Discrete(100))

In [10]:
graph.sample(num_nodes=1)

GraphInstance(nodes=array([[[4, 4, 3],
        [0, 2, 3],
        [2, 4, 4]]]), edges=None, edge_links=None)

In [11]:
box.sample()

array([[4, 2, 2],
       [0, 1, 1],
       [2, 0, 4]])

In [12]:
import numpy as np
import copy
x=np.array([[0,0], [0,0]])


In [13]:
x.shape

(2, 2)

In [14]:
matricesList = []
numberOfTypes = 2
size = 2

instance = np.array([0,0,0,0])

def generateSetOfInstances(instance, depth):

    if depth > 3:
        return
    
    for i in range(0, numberOfTypes + 1):
        newInstance = copy.deepcopy(instance)
        newInstance[depth] = i
        matricesList.append(newInstance)
        generateSetOfInstances(newInstance, depth + 1)


In [15]:
generateSetOfInstances(instance, 0)

In [16]:
matricesList

[array([0, 0, 0, 0]),
 array([0, 0, 0, 0]),
 array([0, 0, 0, 0]),
 array([0, 0, 0, 0]),
 array([0, 0, 0, 1]),
 array([0, 0, 0, 2]),
 array([0, 0, 1, 0]),
 array([0, 0, 1, 0]),
 array([0, 0, 1, 1]),
 array([0, 0, 1, 2]),
 array([0, 0, 2, 0]),
 array([0, 0, 2, 0]),
 array([0, 0, 2, 1]),
 array([0, 0, 2, 2]),
 array([0, 1, 0, 0]),
 array([0, 1, 0, 0]),
 array([0, 1, 0, 0]),
 array([0, 1, 0, 1]),
 array([0, 1, 0, 2]),
 array([0, 1, 1, 0]),
 array([0, 1, 1, 0]),
 array([0, 1, 1, 1]),
 array([0, 1, 1, 2]),
 array([0, 1, 2, 0]),
 array([0, 1, 2, 0]),
 array([0, 1, 2, 1]),
 array([0, 1, 2, 2]),
 array([0, 2, 0, 0]),
 array([0, 2, 0, 0]),
 array([0, 2, 0, 0]),
 array([0, 2, 0, 1]),
 array([0, 2, 0, 2]),
 array([0, 2, 1, 0]),
 array([0, 2, 1, 0]),
 array([0, 2, 1, 1]),
 array([0, 2, 1, 2]),
 array([0, 2, 2, 0]),
 array([0, 2, 2, 0]),
 array([0, 2, 2, 1]),
 array([0, 2, 2, 2]),
 array([1, 0, 0, 0]),
 array([1, 0, 0, 0]),
 array([1, 0, 0, 0]),
 array([1, 0, 0, 0]),
 array([1, 0, 0, 1]),
 array([1,

In [17]:
import itertools

In [19]:
for i in itertools.combinations_with_replacement(range(0,3), 4):
    i = np.array(i)
    i = i.reshape((2,2))
    print(i)

[[0 0]
 [0 0]]
[[0 0]
 [0 1]]
[[0 0]
 [0 2]]
[[0 0]
 [1 1]]
[[0 0]
 [1 2]]
[[0 0]
 [2 2]]
[[0 1]
 [1 1]]
[[0 1]
 [1 2]]
[[0 1]
 [2 2]]
[[0 2]
 [2 2]]
[[1 1]
 [1 1]]
[[1 1]
 [1 2]]
[[1 1]
 [2 2]]
[[1 2]
 [2 2]]
[[2 2]
 [2 2]]
